---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.0.3
serverless_language: 
polling_url: https://telescopius-proxy.jonathan-poh.workers.dev
polling_headers: ''
polling_body: ''
id: 227426
name: Telescopius
refresh_interval: 1440
